[project]
name = "quant-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ccxt>=4.5.40",
    "jupyterlab>=4.5.5",
    "matplotlib>=3.9.4",
    "pandas>=2.3.3",
]
